apiVersion: v1
kind: ConfigMap
metadata:
  name: common-event-store
  namespace: qa
data:
  EVENTSTORE_DB_HOST: interop-platform-data-qa.cluster-cwgb5whmdqov.eu-south-1.rds.amazonaws.com
  EVENTSTORE_DB_NAME: persistence_management
  EVENTSTORE_DB_PORT: '5432'
