apiVersion: v1
kind: ConfigMap
metadata:
  name: common-kafka
  namespace: qa
data:
  AGREEMENT_OUTBOUND_TOPIC: "outbound.qa_agreement.events"
  AGREEMENT_TOPIC: "event-store.qa_agreement.events"
  APPLICATION_AUDIT_TOPIC: "qa_application.audit"
  ATTRIBUTE_TOPIC: "event-store.qa_attribute_registry.events"
  AUTHORIZATION_TOPIC: "event-store.qa_authorization.events"
  CATALOG_OUTBOUND_TOPIC: "outbound.qa_catalog.events"
  CATALOG_TOPIC: "event-store.qa_catalog.events"
  DELEGATION_TOPIC: "event-store.qa_delegation.events"
  ESERVICE_TEMPLATE_TOPIC: "event-store.qa_eservice_template.events"
  KAFKA_BROKERS: "b-2.interopplatformevents.js15v7.c4.kafka.eu-south-1.amazonaws.com:9098,b-1.interopplatformevents.js15v7.c4.kafka.eu-south-1.amazonaws.com:9098,b-3.interopplatformevents.js15v7.c4.kafka.eu-south-1.amazonaws.com:9098"
  PURPOSE_OUTBOUND_TOPIC: "outbound.qa_purpose.events"
  PURPOSE_TOPIC: "event-store.qa_purpose.events"
  TENANT_OUTBOUND_TOPIC: "outbound.qa_tenant.events"
  TENANT_TOPIC: "event-store.qa_tenant.events"
  TOKEN_AUDITING_TOPIC: "qa_authorization-server.generated-jwt"