name: "interop-be-token-details-persister"

serviceAccount:
  roleArn: "arn:aws:iam::505630707203:role/interop-iam-service-dev-interop-be-token-details-persister-es1"

configmap:
  JWT_QUEUE_NAME: "generated-jwt"
  TOKENS_JOB_BUCKET: "interop-generated-jwt-details-dev-es1"
  TOKENS_JOB_BASE_DOCS_PATH: "token-details"
  QUEUE_VISIBILITY_TIMEOUT_IN_SECONDS: "60"
  MAX_NUMBER_OF_MESSAGES_PER_FILE: "1000"

cronjob:
  schedule: "0 */1 * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 0
  restartPolicy: OnFailure
  automountServiceAccountToken: false
  command: ["bin/interop-be-token-details-persister"]
  args: ["-Dconfig.override_with_env_vars=true"]
  env:
    JWT_QUEUE_URL: "https://sqs.eu-south-1.amazonaws.com/505630707203/generated-jwt"
  envFromFieldRef:
    NAMESPACE: "metadata.namespace"
  resources:
    requests:
      cpu: "1"
      memory: "2Gi"
    limits:
      cpu: "1"
      memory: "2Gi"