name: "redis"
techStack: "nodejs"

service:
  create: true
  containerPort: 6379
  targetPort: 6379
  name: redis
  protocol: TCP

deployment:
  image:
    repositoryPrefix: docker.io
    repositoryName: "redis"
  command: ["redis-server"]
  args: ["--save", "''", "--appendonly", "no"]
  livenessProbe:
  readinessProbe: