name: "interop-be-authorization-updater"
techStack: "nodejs"

serviceAccount:
  roleArn: "arn:aws:iam::505630707203:role/interop-be-authorization-updater-dev-es1"

service:
  create: false
  
configmap:
  KAFKA_CLIENT_ID: "{{.Values.namespace}}-pagopa-interop-authorization-updater"
  KAFKA_GROUP_ID: "{{.Values.namespace}}-authorization-updater"
  INTERNAL_JWT_KID: "{{.Values.local.interop_be_commons.RSA_KEYS_IDENTIFIERS}}"
  INTERNAL_JWT_ISSUER: "{{.Values.namespace}}.interop.pagopa.it"
  INTERNAL_JWT_AUDIENCE: "{{.Values.namespace}}.interop.pagopa.it/internal"
  INTERNAL_JWT_SECONDS_DURATION: "3600"  
  INTERNAL_JWT_SUBJECT: "{{.Values.namespace}}.interop-m2m"

deployment:
  env:
    TOPIC_STARTING_OFFSET: "latest"
  envFromFieldRef:
    AWS_ROLE_SESSION_NAME: "metadata.name"
  envFromConfigmaps:
    KAFKA_BROKERS: "common-kafka.KAFKA_BROKERS"
    AGREEMENT_TOPIC: "common-kafka.AGREEMENT_TOPIC"
    CATALOG_TOPIC: "common-kafka.CATALOG_TOPIC"
    PURPOSE_TOPIC: "common-kafka.PURPOSE_TOPIC"
    AUTHORIZATION_TOPIC: "common-kafka.AUTHORIZATION_TOPIC"
    AUTHORIZATION_MANAGEMENT_URL: "common-services-urls.AUTHORIZATION_MANAGEMENT_URL"
    READMODEL_DB_HOST: "common-read-model.READMODEL_DB_HOST"
    READMODEL_DB_NAME: "common-read-model.READMODEL_DB_NAME"
    READMODEL_DB_PORT: "common-read-model.READMODEL_DB_PORT"
  envFromSecrets:
    READMODEL_DB_USERNAME: "read-model.READONLY_USR"
    READMODEL_DB_PASSWORD: "read-model.READONLY_PSW"