name: interop-be-eservice-template-readmodel-writer
techStack: "nodejs"

serviceAccount:
  roleArn: "arn:aws:iam::505630707203:role/interop-be-eservice-template-readmodel-writer-dev-es1"

service:
  create: false

configmap:
  KAFKA_CLIENT_ID: "{{.Values.namespace}}-pagopa-interop-eservice-template"
  KAFKA_GROUP_ID: "{{.Values.namespace}}-eservice-template-readmodel-writer"

deployment:
  env:
    PORT: "8088"
    HOST: "0.0.0.0"
    TOPIC_STARTING_OFFSET: "earliest" 
  envFromConfigmaps:
    KAFKA_BROKERS: "common-kafka.KAFKA_BROKERS"
    ESERVICE_TEMPLATE_TOPIC: "common-kafka.ESERVICE_TEMPLATE_TOPIC"
    READMODEL_DB_HOST: "common-read-model.READMODEL_DB_HOST"
    READMODEL_DB_NAME: "common-read-model.READMODEL_DB_NAME"
    READMODEL_DB_PORT: "common-read-model.READMODEL_DB_PORT"
  envFromSecrets:
    READMODEL_DB_USERNAME: "read-model.PROJECTION_USR"
    READMODEL_DB_PASSWORD: "read-model.PROJECTION_PSW"
  envFromFieldRef:
    AWS_ROLE_SESSION_NAME: "metadata.name"
