name: "interop-frontend"
techStack: "frontend"

service:
  create: true
  containerPort: 80
  targetPort: 80
  albHealthCheck:
    path: "/nginx-status"
    successCodes: "200"

frontend:
  nginx:
    default.conf: |-
      server {
        listen       80;
        listen  [::]:80;
        server_name  localhost;
        absolute_redirect off;

        location /ui {
          root   /usr/share/nginx/html;
          sub_filter_once off;
          sub_filter_types *;
          sub_filter **CSP_NONCE** $request_id;
          add_header Content-Security-Policy "default-src 'self'; object-src 'none'; connect-src 'self' https://api-eu.mixpanel.com https://privacyportal-de.onetrust.com https://interop-application-import-export-dev-es1.s3.eu-south-1.amazonaws.com https://interop-application-import-export-dev-es1.s3.eu-south-1.amazonaws.com https://interop-dev-public-es1.s3.eu-south-1.amazonaws.com; script-src 'nonce-$request_id'; style-src 'self' 'unsafe-inline'; worker-src 'none'; font-src 'self'; img-src 'self' https://interop-dev-public-es1.s3.eu-south-1.amazonaws.com data:; base-uri 'self'";
          add_header Strict-Transport-Security "max-age=31536000";
          add_header X-Content-Type-Options "nosniff";
          add_header X-Frame-Options "SAMEORIGIN";
          add_header Referrer-Policy "no-referrer";
          rewrite /ui/index.html /ui permanent;
          try_files $uri /ui/index.html =404;
        }

        location /nginx-status {
          access_log off;
          return 200;
        }

        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
          root   /usr/share/nginx/html;
        }
      }
  additionalAssets: 
    env.js: |- 
      window.pagopa_env = {
        STAGE: "DEV",
        AUTHORIZATION_SERVER_TOKEN_CREATION_URL: "https://auth.dev.interop.pagopa.it/token.oauth2",
        SELFCARE_LOGIN_URL: "https://uat.selfcare.pagopa.it/auth/login",
        INTEROP_RESOURCES_BASE_URL: "https://interop-dev-public-es1.s3.eu-south-1.amazonaws.com",
        BACKEND_FOR_FRONTEND_URL: "https://selfcare.dev.interop.pagopa.it/0.0/backend-for-frontend",
        API_GATEWAY_INTERFACE_URL: "https://selfcare.dev.interop.pagopa.it/m2m/interface-specification.yaml",
        MIXPANEL_PROJECT_ID: "b6c8c3c3ed0b32d66c61593bcb84e705",
        ONETRUST_DOMAIN_SCRIPT_ID: "018ef6c1-31f6-70a6-bf72-d7d45c0ade7e",
        CLIENT_ASSERTION_JWT_AUDIENCE: "auth.dev.interop.pagopa.it/client-assertion",
        M2M_JWT_AUDIENCE: "dev.interop.pagopa.it/m2m",
        WELL_KNOWN_URLS : "https://dev.interop.pagopa.it/.well-known/jwks.json",
        PRODUCER_ALLOWED_ORIGINS : "IPA",
        SELFCARE_BASE_URL : "https://uat.selfcare.pagopa.it",
        API_SIGNAL_HUB_PUSH_INTERFACE_URL : "https://raw.githubusercontent.com/pagopa/interop-signalhub-core/refs/heads/develop/docs/openAPI/push-signals.yaml",
        API_SIGNAL_HUB_PULL_INTERFACE_URL : "https://raw.githubusercontent.com/pagopa/interop-signalhub-core/refs/heads/develop/docs/openAPI/pull-signals.yaml",
        FEATURE_FLAG_SIGNALHUB_WHITELIST : "true",
        SIGNALHUB_WHITELIST_CONSUMER : "69e2865e-65ab-4e48-a638-2037a9ee2ee7,e79a24cd-8edc-441e-ae8d-e87c3aea0059",
        SIGNALHUB_WHITELIST_PRODUCER : "69e2865e-65ab-4e48-a638-2037a9ee2ee7",
        FEATURE_FLAG_AGREEMENT_APPROVAL_POLICY_UPDATE: "true"
      }
