name: "interop-be-purpose-readmodel-writer"
techStack: "nodejs"

serviceAccount:
  roleArn: "arn:aws:iam::755649575658:role/interop-be-purpose-readmodel-writer-qa-es1"

service:
  create: false

configmap:
  KAFKA_CLIENT_ID: "{{.Values.namespace}}-pagopa-interop-purpose"
  KAFKA_GROUP_ID: "{{.Values.namespace}}-purpose-readmodel-writer"

deployment:
  env:
    PORT: "8088"
    HOST: "0.0.0.0"
    TOPIC_STARTING_OFFSET: "earliest"
  envFromFieldRef:
    AWS_ROLE_SESSION_NAME: "metadata.name"
  envFromConfigmaps:
    PURPOSE_TOPIC: "common-kafka.PURPOSE_TOPIC"
    KAFKA_BROKERS: "common-kafka.KAFKA_BROKERS"
    READMODEL_DB_HOST: "common-read-model.READMODEL_DB_HOST"
    READMODEL_DB_NAME: "common-read-model.READMODEL_DB_NAME"
    READMODEL_DB_PORT: "common-read-model.READMODEL_DB_PORT"
  envFromSecrets:
    READMODEL_DB_USERNAME: "read-model.PROJECTION_USR"
    READMODEL_DB_PASSWORD: "read-model.PROJECTION_PSW"