name: "interop-be-anac-certified-attributes-importer"

serviceAccount:
  roleArn: "arn:aws:iam::755649575658:role/interop-be-anac-certified-attributes-importer-qa-es1"

configmap:
  SFTP_PORT: "22"
  SFTP_PATH: "qa"
  SFTP_FILENAME_PREFIX: "qa"
  INTERNAL_JWT_KID: "{{.Values.local.interop_be_commons.RSA_KEYS_IDENTIFIERS}}"
  INTERNAL_JWT_SUBJECT: "qa.interop-m2m"
  INTERNAL_JWT_ISSUER: "qa.interop.pagopa.it"
  INTERNAL_JWT_AUDIENCE: "qa.interop.pagopa.it/internal"
  INTERNAL_JWT_SECONDS_DURATION: "1800"
  ANAC_TENANT_ID: "e99c1081-8fcb-4701-a461-ac2725b18fe7"
  RECORDS_PROCESS_BATCH_SIZE: "100"

cronjob:
  schedule: "15 5,11,17,23 * * *"
  suspend: true
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 0
  restartPolicy: OnFailure
  envFromFieldRef:
    NAMESPACE: "metadata.namespace"
  envFromConfigmaps:
    TENANT_PROCESS_URL: "common-services-urls.TENANT_PROCESS_URL"
    READ_MODEL_DB_HOST: "common-read-model.READMODEL_DB_HOST"
    READ_MODEL_DB_NAME: "common-read-model.READMODEL_DB_NAME"
    READ_MODEL_DB_PORT: "common-read-model.READMODEL_DB_PORT"
    MONGODB_REPLICA_SET: "common-read-model.READMODEL_REPLICA_SET"
    MONGODB_READ_PREFERENCE: "common-read-model.READMODEL_READ_PREFERENCE"
  envFromSecrets:
    READ_MODEL_DB_USER: "documentdb.READONLY_USR"
    READ_MODEL_DB_PASSWORD: "documentdb.READONLY_PSW"
    SFTP_HOST: "anac.SFTP_HOST"
    SFTP_USERNAME: "anac.SFTP_USERNAME"
    SFTP_PASSWORD: "anac.SFTP_PASSWORD"
