name: "interop-be-anac-certified-attributes-importer"

serviceAccount:
  roleArn: "arn:aws:iam::505630707203:role/interop-be-anac-certified-attributes-importer-dev-es1"

configmap:
  SFTP_PORT: "22"
  SFTP_PATH: "dev"
  SFTP_FILENAME_PREFIX: "dev"
  ANAC_TENANT_ID: "e99c1081-8fcb-4701-a461-ac2725b18fe7"
  RECORDS_PROCESS_BATCH_SIZE: "100"
  INTERNAL_JWT_KID: "41e3a8e9-5982-4a6d-b531-850774bfd961"
  INTERNAL_JWT_SUBJECT: "dev.interop-m2m"
  INTERNAL_JWT_ISSUER: "dev.interop.pagopa.it"
  INTERNAL_JWT_AUDIENCE: "dev.interop.pagopa.it/internal"
  INTERNAL_JWT_SECONDS_DURATION: "1800"

cronjob:
  schedule: "15 5,11,17,23 * * *"
  failedJobsHistoryLimit: 1
  successfulJobsHistoryLimit: 0
  restartPolicy: OnFailure
  automountServiceAccountToken: false
  envFromFieldRef:
    NAMESPACE: "metadata.namespace"
  envFromConfigmaps:
    READMODEL_DB_HOST: "common-read-model.READMODEL_DB_HOST"
    READMODEL_DB_PORT: "common-read-model.READMODEL_DB_PORT"
    READMODEL_DB_NAME: "common-read-model.READMODEL_DB_NAME"
    MONGODB_REPLICA_SET: "common-read-model.READMODEL_REPLICA_SET"
    MONGODB_READ_PREFERENCE: "common-read-model.READMODEL_READ_PREFERENCE"
    TENANT_PROCESS_URL: "common-services-urls.TENANT_PROCESS_URL"
  envFromSecrets:
    READMODEL_DB_USERNAME: "documentdb.READONLY_USR"
    READMODEL_DB_PASSWORD: "documentdb.READONLY_PSW"
    SFTP_HOST: "anac.SFTP_HOST"
    SFTP_USERNAME: "anac.SFTP_USERNAME"
    SFTP_PASSWORD: "anac.SFTP_PASSWORD"