name: "interop-be-compute-agreements-consumer"
techStack: "nodejs"

serviceAccount:
  roleArn: "arn:aws:iam::565393043798:role/interop-be-compute-agreements-consumer-vapt-es1"

service:
  create: false
  
configmap:
  KAFKA_CLIENT_ID: "{{.Values.namespace}}-pagopa-interop-compute-agreements-consumer"
  KAFKA_GROUP_ID: "{{.Values.namespace}}-compute-agreements-consumer"
  INTERNAL_JWT_KID: "{{.Values.local.interop_be_commons.RSA_KEYS_IDENTIFIERS}}"
  INTERNAL_JWT_ISSUER: "{{.Values.namespace}}.interop.pagopa.it"
  INTERNAL_JWT_SUBJECT: "{{.Values.namespace}}.interop-m2m"
  INTERNAL_JWT_AUDIENCE: "{{.Values.namespace}}.interop.pagopa.it/internal"
  INTERNAL_JWT_SECONDS_DURATION: "3600"

deployment:
  env:
    TOPIC_STARTING_OFFSET: "latest"
  envFromFieldRef:
    AWS_ROLE_SESSION_NAME: "metadata.name"
  envFromConfigmaps:
    AGREEMENT_PROCESS_URL: "common-services-urls.AGREEMENT_PROCESS_URL"
    TENANT_TOPIC: "common-kafka.TENANT_TOPIC"
    KAFKA_BROKERS: "common-kafka.KAFKA_BROKERS"
