name: "interop-be-eservice-descriptors-archiver"
techStack: "nodejs"

serviceAccount:
  roleArn: "arn:aws:iam::755649575658:role/interop-be-eservice-descriptors-archiver-qa-es1"

service:
  create: false
  
configmap:
  KAFKA_CLIENT_ID: "{{.Values.namespace}}-pagopa-interop-eservice-descriptors-archiver"
  KAFKA_GROUP_ID: "{{.Values.namespace}}-eservice-descriptors-archiver"
  INTERNAL_JWT_KID: "{{.Values.local.interop_be_commons.RSA_KEYS_IDENTIFIERS}}"
  INTERNAL_JWT_ISSUER: "{{.Values.namespace}}.interop-eservice-descriptors-archiver"
  INTERNAL_JWT_SUBJECT: "{{.Values.namespace}}.interop-m2m"
  INTERNAL_JWT_AUDIENCE: "{{.Values.namespace}}.interop.pagopa.it/internal"
  INTERNAL_JWT_SECONDS_DURATION: "3600"

deployment:
  env:
    TOPIC_STARTING_OFFSET: "latest"
  envFromFieldRef:
    NAMESPACE: "metadata.namespace"
    AWS_ROLE_SESSION_NAME: "metadata.name"
  envFromConfigmaps:
    CATALOG_PROCESS_URL: "common-services-urls.CATALOG_PROCESS_URL"
    READMODEL_DB_NAME: "common-read-model.READMODEL_DB_NAME"
    READMODEL_DB_PORT: "common-read-model.READMODEL_DB_PORT"
    READMODEL_DB_HOST: "common-read-model.READMODEL_DB_HOST"
    AGREEMENT_TOPIC: "common-kafka.AGREEMENT_TOPIC"
    KAFKA_BROKERS: "common-kafka.KAFKA_BROKERS"
  envFromSecrets:
    READMODEL_DB_USERNAME: "read-model.READONLY_USR"
    READMODEL_DB_PASSWORD: "read-model.READONLY_PSW"
    
