
name: Local Test Deploy-Sub

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to run apply against'
        required: true
        default: 'qa'
      timeout_seconds:
        description: 'Kubectl apply wait timeout in seconds for Deployments'
        required: true
        default: '150'

jobs:
  call-deploy-sub:
    uses: ./.github/workflows/deploy-sub.yaml
    with:
      environment: ${{ github.event.inputs.environment }}
      timeout_seconds: ${{ github.event.inputs.timeout_seconds }}
    secrets: inherit
