name: Local Test Deploy-Sub

on: workflow_dispatch

jobs:
  call-deploy-sub:
    uses: ./interop-core-deployment/.github/workflows/deploy-sub.yaml
    with:
      environment: qa            
      timeout_seconds: 120       
