##name: PR Validation - Main Starter
##
##on:
##  pull_request:
##    types: [opened, edited, reopened, synchronize]
##
##permissions:
##  id-token: write
##  contents: read
##
##jobs:      
##  start_dev_workflow:
##    uses: ./.github/workflows/pr-validation-generic-env.yaml
##    secrets: inherit
##    with:
##      environment: dev
##  
##  diff_summary:
##    needs: [ start_dev_workflow ]
##    if: ${{ vars.ENABLE_KUBE_DIFF == 'true' }}
##    secrets: inherit
##    uses: ./.github/workflows/pr-validation-sub-print-summary.yaml
##

#name: PR Validation - Main Starter
#
#on:
#  workflow_dispatch:
#
#permissions:
#  id-token: write
#  contents: read
#
#jobs:
#  validation:
#    name: "Validation – ${{ matrix.environment }}"
#    runs-on: ubuntu-latest
#    strategy:
#      matrix:
#        environment: [dev, qa, vapt]
#    steps:
#      - uses: actions/checkout@v4
#      - name: Executing validation
#        uses: roberto-mondello-dgt/interop-core-deployment/actions/deployment-values-validation@v1
#        with:
#          environment: ${{ matrix.environment }}


name: PR Validation - Main Starter

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  validation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, qa, vapt]  # Qui puoi aggiungere altri env se vuoi!
    steps:
      - name: EExecuting validation
        uses: roberto-mondello-dgt/interop-core-deployment/actions/deployment-values-validation@v1
        with:
          environment: ${{ matrix.environment }}
          #infra_commons_tag: "v1.0.0"  # Cambia con il tag reale di interop-infra-commons!
