name: PR Validation - Main Starter

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  validation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, qa, vapt]  # Qui puoi aggiungere altri env se vuoi!
    steps:
      - name: EExecuting validation
        uses: roberto-mondello-dgt/interop-core-deployment/actions/deployment-values-validation@v1
        with:
          environment: ${{ matrix.environment }}
          #infra_commons_tag: "v1.0.0"  # Cambia con il tag reale di interop-infra-commons!
