name: PR Validation - Main Starter

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  validation:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        environment: [dev, qa, vapt]
    steps:
      - name: EExecuting validation
        uses: roberto-mondello-dgt/interop-core-deployment/actions/deployment-values-validation@main
        with:
          environment: ${{ matrix.environment }}
          infra_commons_tag: main 
